version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    dockerfile: laravel_app
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./.env:/var/www/laravel-developer-test/.env
    environment:
      - APP_ENV=local
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue_app
    ports:
      - "8080:8080"
    volumes:
      - ./user-maintenance-app
    stdin_open: true
    tty: true
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel-test
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
